#!/bin/bash

bgBlack=$(tput setab 0)         # black
bgRed=$(tput setab 1)           # red
bgGreen=$(tput setab 2)         # green
bgYellow=$(tput setab 3)        # yellow
bgBlue=$(tput setab 4)          # blue
bgMagenta=$(tput setab 5)       # magenta
bgCyan=$(tput setab 6)          # cyan
bgWhite=$(tput setab 7)         # white

# foreground color using ANSI escape

fgBlack=$(tput setaf 0)         # black
fgRed=$(tput setaf 1)           # red
fgGreen=$(tput setaf 2)         # green
fgYellow=$(tput setaf 3)        # yellow
fgBlue=$(tput setaf 4)          # blue
fgMagenta=$(tput setaf 5)       # magenta
fgCyan=$(tput setaf 6)          # cyan
fgWhite=$(tput setaf 7)         # white

# text editing options

txBold=$(tput bold)             # bold
txHalf=$(tput dim)              # half-bright
txUnderline=$(tput smul)        # underline
txEndUnder=$(tput rmul)         # exit underline
txReverse=$(tput rev)           # reverse
txStandout=$(tput smso)         # standout
txEndStand=$(tput rmso)         # exit standout
txReset=$(tput sgr0)            # reset attributes
txItalic=$(tput sitm)           # italic




### echo -en "\033]0;AARYAS TOOLBOX V.0.0.0, RELEASE DATE 28. Nov 2022\a" ### Tried to change the title of the window, dIdNt reALlY wOrk


# Name of the program: 
echo " █████╗ ██╗  ██╗    ████████╗ ██████╗  ██████╗ ██╗     ██████╗  ██████╗ ██╗  ██╗";
echo "██╔══██╗╚██╗██╔╝    ╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔══██╗██╔═══██╗╚██╗██╔╝";
echo "███████║ ╚███╔╝        ██║   ██║   ██║██║   ██║██║     ██████╔╝██║   ██║ ╚███╔╝ ";
echo "██╔══██║ ██╔██╗        ██║   ██║   ██║██║   ██║██║     ██╔══██╗██║   ██║ ██╔██╗ ";
echo "██║  ██║██╔╝ ██╗       ██║   ╚██████╔╝╚██████╔╝███████╗██████╔╝╚██████╔╝██╔╝ ██╗";
echo "╚═╝  ╚═╝╚═╝  ╚═╝       ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝";
echo "                                                                                ";
echo "${fgBlack}${bgRed}${txItalic}Version not assigned yet, build created on ${txUnderline}28. Nov 2022${txReset}."
